simple test not finding selenium deps. java.lang.NoClassDefFoundError: org/openqa/selenium/support/events/EventFiringWebDriver Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.support.events.EventFiringWebDriver